### PR TITLE
Fix disabling autocomplete 

### PR DESCRIPTION
**Pull request by Anenth**
Right now the input shows the browser auto-complete, this change will fix the disabling of auto-complete

Fixes issue #43

### CODE REVIEW

**Comment by LeakedDave** [comment]
Merge plz ^__^

**Comment by Anenth** [comment]
@ErrorPro can we merge this?

**Comment by groovychoons** [comment]
Hey, wanted to bump this to see if you could merge?

**Comment by ErrorPro** [comment]
@Anenth Sorry for the delay guys. Merged and released in 1.1.3. Thanks.

**Comment by Anenth** [comment]
@ErrorPro thanks alot

**Pull request merged**
