### PR TITLE
Propagate bounds changes

### PR DESCRIPTION
**Pull request by mlucool**

### CODE REVIEW

**Comment by mlucool** [comment]
I did not take care of types as the cleanest way would require a little bit of a refactor due to where defaults are set.

**Comment by ErrorPro** [comment]
@mlucool Thanks for your PR, but I think maybe it's better to take a ref passed from the parent component and pass it down to the input, so you would have access to the input instance inside your component? smth like this:

```
class A extends Component {
   // now you can do whatever you like with this.input.
   input = React.createRef();

  render() {
    return <Autocomplete {...this.props} ref={this.input} />
}

**Comment by mlucool** [comment]
I disagree as this component should work as props change without someone having to wrap it in any way.

**Comment by ErrorPro** [comment]
what if someone doesn't want that behaviour in componentDidUpdate? They will have it anyway, so you think this is better than asking to pass ref as a prop?

**Comment by ErrorPro** [comment]
I don't mind merging the PR, just trying to understand if that will affect someone else

**Comment by mlucool** [comment]
If they really didn't want it to work like this, they should extend and override this method. Given that react is declarative in nature, all components should always honor prop changes correctly.

**Comment by hungvtitdng** [comment]
can you merge this PR to master? This resolved this issue `83`

**Comment by ErrorPro** [comment]
@mlucool Hey Marc, thanks for your PR and I finally found some time to rework the lib and add that feature and some more!

**Pull request closed without merging**
